---
# tasks file for amirInstallingApache
- name: httpd installing
  yum:
    name: httpd
    state: latest
- name: httpd service enabled
  service:
    name: httpd
    enabled: true
    state: started
- name: open firewall
  firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true
...
